#!/usr/bin/env bash
# A Bash script that displays the visitor IP along with HTTP status code
# from the Apache log file
# Parses Apache log files in list format.

awk '{print $1 " " $9}' apache-access.log
